= Test and automate with HIL

== Deploy the OS image using Jumpstarter and do some simple hardware-in-the-loop (HIL) testing

In the previous section, we've build an RHIVOS image and pushed it to minio, and now we can flash the image to the virtual hardware for further testing.

. Verify the image is uploaded

+
[source,bash]
----
mc ls minio/$USER
----
+
NOTE: While the image is stored in a private bucket, jumpstarter would take care of generating presigned URLs so that the exporter can access it without prior configuration.

. Enter a jumpstarter shell session connecting to the designated virtual device

+
[source,bash]
----
jmp client shell --selector jumpstarter.dev/board=virtual
----
+
NOTE: Your shell prompt would be changed to "<placeholder>" to indicate that you are in a jumpstarter session

. Flash the image

+
[source,bash]
----
j flasher flash --scheme s3 --endpoint $(mc alias export minio | jq -r .url) --bucket $USER <name of image file>
----
+
NOTE: The `j` command is only available in a jumpstarter shell session, it is dynamically generated based on the interfaces available on the connected device.

== Interact with the DUT remotely, using the Jumpstarter CLI

Now that the image is flashed, we can boot and interact with the virtual device with the `j` CLI.

+
[source,bash]
----
j power on
j console start-console
----
+

You would be dropped into a serial console with the boot messages showing up, and presented with a login prompt shortly after. You can login with the default username "jumpstarter" and password "password", and feel free to explore the RHIVOS environment on you own.

== Write tests to validate the application

== Run the written tests in pipelines
