= Test and automate with HIL

== First steps with Jumpstarter

Jumpstarter is already pre-installed in the developer workspace, you can check for it with

[source,bash]
----
jmp version
----

Jumpstarter interacts with hardware interfaces through "drivers", drivers are written in python to make use of the vast ecosystem of existing python packages. While you can always extend Jumpstarter by writing your own drivers, it comes with a collection of general purpose drivers to help you get started.

[source,bash]
----
jmp driver list
----

TIP: Among the drivers you would notice a few with "mock" in their names, while these mock drivers do not provide access to the hardware, they are useful in showcasing the capability of Jumpstarter

=== Configuring Jumpstarter for local development

Create a new file in the workspace named `first-steps.yaml`, this would be an "exporter config file". Within which we would configure a list of drivers representing the hardware interfaces we would like to "export" to the users (that happens to be ourselves in this case).

.first-steps.yaml
[source,yaml]
----
apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  namespace: default
  name: first-steps
endpoint: ""
token: ""
export:
  power:
    # provides power management: power on/off/cycle
    type: jumpstarter_driver_power.driver.MockPower
  console:
    # provides serial console access
    type: jumpstarter_driver_pyserial.driver.PySerial
    config:
      url: "loop://" # a mock serial port that echos everything
  flasher:
    # provides storage access: like flashing a disk image into a sdcard
    type: jumpstarter_driver_opendal.driver.MockFlasher
----

NOTE: endpoint and token are intentionally left empty here, since they are only useful for remote access workflows.

Now we can enter the exporter shell, within which a transient Jumpstarter exporter would be started and made available for us to interact with.

[source,bash]
----
jmp shell --exporter-config ./first-steps.yaml
----

TIP: Notice that you shell prompt have been changed to `jumpstarter ⚡local ➤`, this is to remind you that you are inside a local Jumpstarter session.

=== Interacting with a local Jumpstarter session with CLI

A `j` command is available inside `jmp shell`, it is dynamically constructed reflecting the drivers configured on the exporter side. Not all dirvers have corresponding CLI interfaces, but it is available on most builtin drivers.

[source,bash]
----
j
----

[NOTE]
====
With our particular configuration in `first-steps.yaml`, you should see something like

....
Usage: j [OPTIONS] COMMAND [ARGS]...

  Generic composite device

Options:
  --help  Show this message and exit.

Commands:
  console  Serial port client
  flasher  Generic flasher interface
  power    Generic power
....
====

Try turning the power of the device under test on and off

[source,bash]
----
j power on
j power off
----

TIP: Nothing actually happens because we are using a mock power driver, but have we configured it with a real power driver, e.g. a USB power relay, you could see the device under test being turned on and off.

In this secion, we've learned how to configure Jumpstarter for local developement and how to interact with the device under test via the `j` command. If you still have time, explore the other subcommands (`j flasher`/`j console`)

== Deploy the OS image using Jumpstarter and do some simple hardware-in-the-loop (HIL) testing

In the previous section, we've build an RHIVOS image and pushed it to minio, and now we can flash the image to the virtual hardware for further testing.

. Verify the image is uploaded

+
[source,bash]
----
mc ls minio/$S3_BUCKET
----
+
NOTE: While the image is stored in a private bucket, jumpstarter would take care of generating presigned URLs so that the exporter can access it without prior configuration.

. Enter a jumpstarter shell session connecting to the designated virtual device

+
[source,bash]
----
jmp client shell --selector jumpstarter.dev/board=virtual
----
+
NOTE: Your shell prompt would be changed to "<placeholder>" to indicate that you are in a jumpstarter session

. Flash the image

+
[source,bash]
----
j flasher flash --scheme s3 --endpoint $S3_ENDPOINT --bucket $S3_BUCKET <name of image file>
----
+
NOTE: The `j` command is only available in a jumpstarter shell session, it is dynamically generated based on the interfaces available on the connected device.

== Interact with the DUT remotely, using the Jumpstarter CLI

Now that the image is flashed, we can boot and interact with the virtual device with the `j` CLI.

[source,bash]
----
j power on
j console start-console
----

You would be dropped into a serial console with the boot messages showing up, and presented with a login prompt shortly after. You can login with the default username "jumpstarter" and password "password", and feel free to explore the RHIVOS environment on your own.

When you are done, exit the console by pressing Ctrl+B 3 times, and you would be dropped back to the jumpstarter shell session.

== Write tests to validate the application

While the jumpstarter CLI interface is well suited for interactive development and testing, it also provides a python API for scripted testing. You may write your test as a regular python script, or in pytest.

[source,python]
----
from jumpstarter.common.utils import env
from opendal import Operator
from os import getenv
import sys

with env() as dut: # reuse the jumpstarter shell session
  dut.power.off()

  dut.flasher.flash(
    "<name of image file>",
    operator=Operator(
      "s3",
      endpoint=getenv("S3_ENDPOINT"),
      bucket=getenv("S3_BUCKET"),
    ),
  )

  dut.power.on()

  with qemu.console.pexpect() as p:
      p.logfile = sys.stdout.buffer # forward console output to stdout
      # login into the dut
      p.expect_exact(f"dut login:", timeout=600)
      p.sendline("jumpstarter")
      p.expect_exact("Password:")
      p.sendline("password")
      # wait for the shell prompt
      p.expect_exact(f"[jumpstarter@dut ~]$")
      # execute test commands
      p.sendline("echo hello from dut")
      p.expect_exact(f"[jumpstarter@dut ~]$")

  dut.power.off()
----

== Run the written tests in pipelines
